# Generated by Django 4.1.7 on 2023-03-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='Establishments',
            new_name='establishments',
        ),
    ]
