# Generated by Django 4.1.7 on 2023-03-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_establishments_description_establishments_sub_photo'),
        ('form', '0003_formhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='formhistory',
            name='establishments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_history_establishmentss', to='project.establishments', verbose_name='Здания'),
        ),
    ]
