# Generated by Django 4.1.7 on 2023-03-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_category_options_qa_establishments'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishments',
            name='description',
            field=models.TextField(null=True, verbose_name='инфо'),
        ),
        migrations.AddField(
            model_name='establishments',
            name='sub_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
